### ISSUE TITLE
endDate not used

### ISSUE THREAD

**Issue by ed1d1a8d** [sipb/sipb-door#5]
endDate is never used in https://github.com/sipb/sipb-door/blob/master/data.cgi.

This results in incorrect behavior, as shown.
<img width="762" alt="screen shot 2017-01-22 at 4 56 01 pm" src="https://cloud.githubusercontent.com/assets/1733389/22186444/02864da6-e0c4-11e6-943c-c2d379b5dafc.png">
Every column except one should be blank.

**Comment by ongmingyang** [comment]
This is good, thanks for patch.
